services:
  postgres:
    image: postgres:16-alpine
    container_name: nastene-postgres
    environment:
      POSTGRES_USER: nastene
      POSTGRES_PASSWORD: nastene
      POSTGRES_DB: nastene
    ports:
      - "5432:5432"
    volumes:
      - nastene-pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nastene -d nastene"]
      interval: 5s
      timeout: 5s
      retries: 10

  minio:
    image: quay.io/minio/minio:latest
    container_name: nastene-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - nastene-minio:/data
    healthcheck:
      test: ["CMD-SHELL", "mc ready local || exit 0"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbit:
    image: rabbitmq:3.13-alpine
    container_name: nastene-rabbit
    ports:
      - "5672:5672"
    volumes:
      - nastene-rabbit:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  nastene-pg:
  nastene-minio:
  nastene-rabbit:
