// Code generated by mockery v2.53.6. DO NOT EDIT.

package wallmocks

import (
	context "context"

	domain "github.com/iamsalnikov/nastene/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CommentRepo is an autogenerated mock type for the CommentRepo type
type CommentRepo struct {
	mock.Mock
}

type CommentRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *CommentRepo) EXPECT() *CommentRepo_Expecter {
	return &CommentRepo_Expecter{mock: &_m.Mock}
}

// ByID provides a mock function with given fields: ctx, id
func (_m *CommentRepo) ByID(ctx context.Context, id int64) (domain.Comment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 domain.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Comment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Comment); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommentRepo_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type CommentRepo_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *CommentRepo_Expecter) ByID(ctx interface{}, id interface{}) *CommentRepo_ByID_Call {
	return &CommentRepo_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *CommentRepo_ByID_Call) Run(run func(ctx context.Context, id int64)) *CommentRepo_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *CommentRepo_ByID_Call) Return(_a0 domain.Comment, _a1 error) *CommentRepo_ByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CommentRepo_ByID_Call) RunAndReturn(run func(context.Context, int64) (domain.Comment, error)) *CommentRepo_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// CountByAuthorSince provides a mock function with given fields: ctx, authorID, since
func (_m *CommentRepo) CountByAuthorSince(ctx context.Context, authorID int64, since time.Time) (int, error) {
	ret := _m.Called(ctx, authorID, since)

	if len(ret) == 0 {
		panic("no return value specified for CountByAuthorSince")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time) (int, error)); ok {
		return rf(ctx, authorID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time) int); ok {
		r0 = rf(ctx, authorID, since)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, time.Time) error); ok {
		r1 = rf(ctx, authorID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommentRepo_CountByAuthorSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByAuthorSince'
type CommentRepo_CountByAuthorSince_Call struct {
	*mock.Call
}

// CountByAuthorSince is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID int64
//   - since time.Time
func (_e *CommentRepo_Expecter) CountByAuthorSince(ctx interface{}, authorID interface{}, since interface{}) *CommentRepo_CountByAuthorSince_Call {
	return &CommentRepo_CountByAuthorSince_Call{Call: _e.mock.On("CountByAuthorSince", ctx, authorID, since)}
}

func (_c *CommentRepo_CountByAuthorSince_Call) Run(run func(ctx context.Context, authorID int64, since time.Time)) *CommentRepo_CountByAuthorSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(time.Time))
	})
	return _c
}

func (_c *CommentRepo_CountByAuthorSince_Call) Return(_a0 int, _a1 error) *CommentRepo_CountByAuthorSince_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CommentRepo_CountByAuthorSince_Call) RunAndReturn(run func(context.Context, int64, time.Time) (int, error)) *CommentRepo_CountByAuthorSince_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, postID, authorID, body
func (_m *CommentRepo) Create(ctx context.Context, postID int64, authorID int64, body string) (domain.Comment, error) {
	ret := _m.Called(ctx, postID, authorID, body)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string) (domain.Comment, error)); ok {
		return rf(ctx, postID, authorID, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string) domain.Comment); ok {
		r0 = rf(ctx, postID, authorID, body)
	} else {
		r0 = ret.Get(0).(domain.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, string) error); ok {
		r1 = rf(ctx, postID, authorID, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommentRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CommentRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
//   - authorID int64
//   - body string
func (_e *CommentRepo_Expecter) Create(ctx interface{}, postID interface{}, authorID interface{}, body interface{}) *CommentRepo_Create_Call {
	return &CommentRepo_Create_Call{Call: _e.mock.On("Create", ctx, postID, authorID, body)}
}

func (_c *CommentRepo_Create_Call) Run(run func(ctx context.Context, postID int64, authorID int64, body string)) *CommentRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *CommentRepo_Create_Call) Return(_a0 domain.Comment, _a1 error) *CommentRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CommentRepo_Create_Call) RunAndReturn(run func(context.Context, int64, int64, string) (domain.Comment, error)) *CommentRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CommentRepo) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CommentRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CommentRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *CommentRepo_Expecter) Delete(ctx interface{}, id interface{}) *CommentRepo_Delete_Call {
	return &CommentRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CommentRepo_Delete_Call) Run(run func(ctx context.Context, id int64)) *CommentRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *CommentRepo_Delete_Call) Return(_a0 error) *CommentRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CommentRepo_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *CommentRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListByPosts provides a mock function with given fields: ctx, postIDs
func (_m *CommentRepo) ListByPosts(ctx context.Context, postIDs []int64) ([]domain.Comment, error) {
	ret := _m.Called(ctx, postIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListByPosts")
	}

	var r0 []domain.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]domain.Comment, error)); ok {
		return rf(ctx, postIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []domain.Comment); ok {
		r0 = rf(ctx, postIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, postIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommentRepo_ListByPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByPosts'
type CommentRepo_ListByPosts_Call struct {
	*mock.Call
}

// ListByPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - postIDs []int64
func (_e *CommentRepo_Expecter) ListByPosts(ctx interface{}, postIDs interface{}) *CommentRepo_ListByPosts_Call {
	return &CommentRepo_ListByPosts_Call{Call: _e.mock.On("ListByPosts", ctx, postIDs)}
}

func (_c *CommentRepo_ListByPosts_Call) Run(run func(ctx context.Context, postIDs []int64)) *CommentRepo_ListByPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *CommentRepo_ListByPosts_Call) Return(_a0 []domain.Comment, _a1 error) *CommentRepo_ListByPosts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CommentRepo_ListByPosts_Call) RunAndReturn(run func(context.Context, []int64) ([]domain.Comment, error)) *CommentRepo_ListByPosts_Call {
	_c.Call.Return(run)
	return _c
}

// NewCommentRepo creates a new instance of CommentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentRepo {
	mock := &CommentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
