// Code generated by mockery v2.53.6. DO NOT EDIT.

package wallmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// FriendshipQuery is an autogenerated mock type for the FriendshipQuery type
type FriendshipQuery struct {
	mock.Mock
}

type FriendshipQuery_Expecter struct {
	mock *mock.Mock
}

func (_m *FriendshipQuery) EXPECT() *FriendshipQuery_Expecter {
	return &FriendshipQuery_Expecter{mock: &_m.Mock}
}

// AreFriends provides a mock function with given fields: ctx, a, b
func (_m *FriendshipQuery) AreFriends(ctx context.Context, a int64, b int64) (bool, error) {
	ret := _m.Called(ctx, a, b)

	if len(ret) == 0 {
		panic("no return value specified for AreFriends")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (bool, error)); ok {
		return rf(ctx, a, b)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) bool); ok {
		r0 = rf(ctx, a, b)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, a, b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FriendshipQuery_AreFriends_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AreFriends'
type FriendshipQuery_AreFriends_Call struct {
	*mock.Call
}

// AreFriends is a helper method to define mock.On call
//   - ctx context.Context
//   - a int64
//   - b int64
func (_e *FriendshipQuery_Expecter) AreFriends(ctx interface{}, a interface{}, b interface{}) *FriendshipQuery_AreFriends_Call {
	return &FriendshipQuery_AreFriends_Call{Call: _e.mock.On("AreFriends", ctx, a, b)}
}

func (_c *FriendshipQuery_AreFriends_Call) Run(run func(ctx context.Context, a int64, b int64)) *FriendshipQuery_AreFriends_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *FriendshipQuery_AreFriends_Call) Return(_a0 bool, _a1 error) *FriendshipQuery_AreFriends_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FriendshipQuery_AreFriends_Call) RunAndReturn(run func(context.Context, int64, int64) (bool, error)) *FriendshipQuery_AreFriends_Call {
	_c.Call.Return(run)
	return _c
}

// HasRequest provides a mock function with given fields: ctx, fromID, toID
func (_m *FriendshipQuery) HasRequest(ctx context.Context, fromID int64, toID int64) (bool, error) {
	ret := _m.Called(ctx, fromID, toID)

	if len(ret) == 0 {
		panic("no return value specified for HasRequest")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (bool, error)); ok {
		return rf(ctx, fromID, toID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) bool); ok {
		r0 = rf(ctx, fromID, toID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, fromID, toID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FriendshipQuery_HasRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasRequest'
type FriendshipQuery_HasRequest_Call struct {
	*mock.Call
}

// HasRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - fromID int64
//   - toID int64
func (_e *FriendshipQuery_Expecter) HasRequest(ctx interface{}, fromID interface{}, toID interface{}) *FriendshipQuery_HasRequest_Call {
	return &FriendshipQuery_HasRequest_Call{Call: _e.mock.On("HasRequest", ctx, fromID, toID)}
}

func (_c *FriendshipQuery_HasRequest_Call) Run(run func(ctx context.Context, fromID int64, toID int64)) *FriendshipQuery_HasRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *FriendshipQuery_HasRequest_Call) Return(_a0 bool, _a1 error) *FriendshipQuery_HasRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FriendshipQuery_HasRequest_Call) RunAndReturn(run func(context.Context, int64, int64) (bool, error)) *FriendshipQuery_HasRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewFriendshipQuery creates a new instance of FriendshipQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFriendshipQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *FriendshipQuery {
	mock := &FriendshipQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
