// Code generated by mockery v2.53.6. DO NOT EDIT.

package wallmocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// GraffitiStore is an autogenerated mock type for the GraffitiStore type
type GraffitiStore struct {
	mock.Mock
}

type GraffitiStore_Expecter struct {
	mock *mock.Mock
}

func (_m *GraffitiStore) EXPECT() *GraffitiStore_Expecter {
	return &GraffitiStore_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, relPath, data
func (_m *GraffitiStore) Save(ctx context.Context, relPath string, data io.Reader) error {
	ret := _m.Called(ctx, relPath, data)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, relPath, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GraffitiStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type GraffitiStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
//   - data io.Reader
func (_e *GraffitiStore_Expecter) Save(ctx interface{}, relPath interface{}, data interface{}) *GraffitiStore_Save_Call {
	return &GraffitiStore_Save_Call{Call: _e.mock.On("Save", ctx, relPath, data)}
}

func (_c *GraffitiStore_Save_Call) Run(run func(ctx context.Context, relPath string, data io.Reader)) *GraffitiStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader))
	})
	return _c
}

func (_c *GraffitiStore_Save_Call) Return(_a0 error) *GraffitiStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GraffitiStore_Save_Call) RunAndReturn(run func(context.Context, string, io.Reader) error) *GraffitiStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewGraffitiStore creates a new instance of GraffitiStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGraffitiStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *GraffitiStore {
	mock := &GraffitiStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
