// Code generated by mockery v2.53.6. DO NOT EDIT.

package wallmocks

import (
	context "context"

	domain "github.com/iamsalnikov/nastene/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// PostRepo is an autogenerated mock type for the PostRepo type
type PostRepo struct {
	mock.Mock
}

type PostRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *PostRepo) EXPECT() *PostRepo_Expecter {
	return &PostRepo_Expecter{mock: &_m.Mock}
}

// ByID provides a mock function with given fields: ctx, id
func (_m *PostRepo) ByID(ctx context.Context, id int64) (domain.WallPost, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 domain.WallPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.WallPost, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.WallPost); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.WallPost)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostRepo_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type PostRepo_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *PostRepo_Expecter) ByID(ctx interface{}, id interface{}) *PostRepo_ByID_Call {
	return &PostRepo_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *PostRepo_ByID_Call) Run(run func(ctx context.Context, id int64)) *PostRepo_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PostRepo_ByID_Call) Return(_a0 domain.WallPost, _a1 error) *PostRepo_ByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PostRepo_ByID_Call) RunAndReturn(run func(context.Context, int64) (domain.WallPost, error)) *PostRepo_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, p
func (_m *PostRepo) Create(ctx context.Context, p domain.WallPost) (domain.WallPost, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.WallPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.WallPost) (domain.WallPost, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.WallPost) domain.WallPost); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(domain.WallPost)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.WallPost) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PostRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.WallPost
func (_e *PostRepo_Expecter) Create(ctx interface{}, p interface{}) *PostRepo_Create_Call {
	return &PostRepo_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *PostRepo_Create_Call) Run(run func(ctx context.Context, p domain.WallPost)) *PostRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.WallPost))
	})
	return _c
}

func (_c *PostRepo_Create_Call) Return(_a0 domain.WallPost, _a1 error) *PostRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PostRepo_Create_Call) RunAndReturn(run func(context.Context, domain.WallPost) (domain.WallPost, error)) *PostRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PostRepo) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PostRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PostRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *PostRepo_Expecter) Delete(ctx interface{}, id interface{}) *PostRepo_Delete_Call {
	return &PostRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *PostRepo_Delete_Call) Run(run func(ctx context.Context, id int64)) *PostRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PostRepo_Delete_Call) Return(_a0 error) *PostRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PostRepo_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *PostRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListByWall provides a mock function with given fields: ctx, ownerID, limit, offset
func (_m *PostRepo) ListByWall(ctx context.Context, ownerID int64, limit int, offset int) ([]domain.WallPost, error) {
	ret := _m.Called(ctx, ownerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByWall")
	}

	var r0 []domain.WallPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]domain.WallPost, error)); ok {
		return rf(ctx, ownerID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) []domain.WallPost); ok {
		r0 = rf(ctx, ownerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.WallPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int) error); ok {
		r1 = rf(ctx, ownerID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostRepo_ListByWall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByWall'
type PostRepo_ListByWall_Call struct {
	*mock.Call
}

// ListByWall is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID int64
//   - limit int
//   - offset int
func (_e *PostRepo_Expecter) ListByWall(ctx interface{}, ownerID interface{}, limit interface{}, offset interface{}) *PostRepo_ListByWall_Call {
	return &PostRepo_ListByWall_Call{Call: _e.mock.On("ListByWall", ctx, ownerID, limit, offset)}
}

func (_c *PostRepo_ListByWall_Call) Run(run func(ctx context.Context, ownerID int64, limit int, offset int)) *PostRepo_ListByWall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *PostRepo_ListByWall_Call) Return(_a0 []domain.WallPost, _a1 error) *PostRepo_ListByWall_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PostRepo_ListByWall_Call) RunAndReturn(run func(context.Context, int64, int, int) ([]domain.WallPost, error)) *PostRepo_ListByWall_Call {
	_c.Call.Return(run)
	return _c
}

// NewPostRepo creates a new instance of PostRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostRepo {
	mock := &PostRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
