// Code generated by mockery v2.53.6. DO NOT EDIT.

package wallmocks

import (
	context "context"

	domain "github.com/iamsalnikov/nastene/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// PrivacyRepo is an autogenerated mock type for the PrivacyRepo type
type PrivacyRepo struct {
	mock.Mock
}

type PrivacyRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *PrivacyRepo) EXPECT() *PrivacyRepo_Expecter {
	return &PrivacyRepo_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, userID
func (_m *PrivacyRepo) Get(ctx context.Context, userID int64) (domain.WallPrivacy, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.WallPrivacy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.WallPrivacy, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.WallPrivacy); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.WallPrivacy)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrivacyRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PrivacyRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *PrivacyRepo_Expecter) Get(ctx interface{}, userID interface{}) *PrivacyRepo_Get_Call {
	return &PrivacyRepo_Get_Call{Call: _e.mock.On("Get", ctx, userID)}
}

func (_c *PrivacyRepo_Get_Call) Run(run func(ctx context.Context, userID int64)) *PrivacyRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PrivacyRepo_Get_Call) Return(_a0 domain.WallPrivacy, _a1 error) *PrivacyRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PrivacyRepo_Get_Call) RunAndReturn(run func(context.Context, int64) (domain.WallPrivacy, error)) *PrivacyRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewPrivacyRepo creates a new instance of PrivacyRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrivacyRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrivacyRepo {
	mock := &PrivacyRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
