// Code generated by mockery v2.53.6. DO NOT EDIT.

package profilemocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// AvatarStore is an autogenerated mock type for the AvatarStore type
type AvatarStore struct {
	mock.Mock
}

type AvatarStore_Expecter struct {
	mock *mock.Mock
}

func (_m *AvatarStore) EXPECT() *AvatarStore_Expecter {
	return &AvatarStore_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, relPath, data
func (_m *AvatarStore) Save(ctx context.Context, relPath string, data io.Reader) error {
	ret := _m.Called(ctx, relPath, data)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, relPath, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AvatarStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type AvatarStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
//   - data io.Reader
func (_e *AvatarStore_Expecter) Save(ctx interface{}, relPath interface{}, data interface{}) *AvatarStore_Save_Call {
	return &AvatarStore_Save_Call{Call: _e.mock.On("Save", ctx, relPath, data)}
}

func (_c *AvatarStore_Save_Call) Run(run func(ctx context.Context, relPath string, data io.Reader)) *AvatarStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader))
	})
	return _c
}

func (_c *AvatarStore_Save_Call) Return(_a0 error) *AvatarStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AvatarStore_Save_Call) RunAndReturn(run func(context.Context, string, io.Reader) error) *AvatarStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewAvatarStore creates a new instance of AvatarStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAvatarStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *AvatarStore {
	mock := &AvatarStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
