// Code generated by mockery v2.53.6. DO NOT EDIT.

package profilemocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// FriendRepo is an autogenerated mock type for the FriendRepo type
type FriendRepo struct {
	mock.Mock
}

type FriendRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *FriendRepo) EXPECT() *FriendRepo_Expecter {
	return &FriendRepo_Expecter{mock: &_m.Mock}
}

// AreFriends provides a mock function with given fields: ctx, a, b
func (_m *FriendRepo) AreFriends(ctx context.Context, a int64, b int64) (bool, error) {
	ret := _m.Called(ctx, a, b)

	if len(ret) == 0 {
		panic("no return value specified for AreFriends")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (bool, error)); ok {
		return rf(ctx, a, b)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) bool); ok {
		r0 = rf(ctx, a, b)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, a, b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FriendRepo_AreFriends_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AreFriends'
type FriendRepo_AreFriends_Call struct {
	*mock.Call
}

// AreFriends is a helper method to define mock.On call
//   - ctx context.Context
//   - a int64
//   - b int64
func (_e *FriendRepo_Expecter) AreFriends(ctx interface{}, a interface{}, b interface{}) *FriendRepo_AreFriends_Call {
	return &FriendRepo_AreFriends_Call{Call: _e.mock.On("AreFriends", ctx, a, b)}
}

func (_c *FriendRepo_AreFriends_Call) Run(run func(ctx context.Context, a int64, b int64)) *FriendRepo_AreFriends_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *FriendRepo_AreFriends_Call) Return(_a0 bool, _a1 error) *FriendRepo_AreFriends_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FriendRepo_AreFriends_Call) RunAndReturn(run func(context.Context, int64, int64) (bool, error)) *FriendRepo_AreFriends_Call {
	_c.Call.Return(run)
	return _c
}

// NewFriendRepo creates a new instance of FriendRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFriendRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *FriendRepo {
	mock := &FriendRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
