// Code generated by mockery v2.53.6. DO NOT EDIT.

package profilemocks

import (
	context "context"

	domain "github.com/iamsalnikov/nastene/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ProfilePrivacyRepo is an autogenerated mock type for the ProfilePrivacyRepo type
type ProfilePrivacyRepo struct {
	mock.Mock
}

type ProfilePrivacyRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ProfilePrivacyRepo) EXPECT() *ProfilePrivacyRepo_Expecter {
	return &ProfilePrivacyRepo_Expecter{mock: &_m.Mock}
}

// EnsureDefaults provides a mock function with given fields: ctx, userID
func (_m *ProfilePrivacyRepo) EnsureDefaults(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for EnsureDefaults")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProfilePrivacyRepo_EnsureDefaults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureDefaults'
type ProfilePrivacyRepo_EnsureDefaults_Call struct {
	*mock.Call
}

// EnsureDefaults is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *ProfilePrivacyRepo_Expecter) EnsureDefaults(ctx interface{}, userID interface{}) *ProfilePrivacyRepo_EnsureDefaults_Call {
	return &ProfilePrivacyRepo_EnsureDefaults_Call{Call: _e.mock.On("EnsureDefaults", ctx, userID)}
}

func (_c *ProfilePrivacyRepo_EnsureDefaults_Call) Run(run func(ctx context.Context, userID int64)) *ProfilePrivacyRepo_EnsureDefaults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ProfilePrivacyRepo_EnsureDefaults_Call) Return(_a0 error) *ProfilePrivacyRepo_EnsureDefaults_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfilePrivacyRepo_EnsureDefaults_Call) RunAndReturn(run func(context.Context, int64) error) *ProfilePrivacyRepo_EnsureDefaults_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, userID
func (_m *ProfilePrivacyRepo) Get(ctx context.Context, userID int64) (domain.ProfilePrivacy, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.ProfilePrivacy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.ProfilePrivacy, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.ProfilePrivacy); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.ProfilePrivacy)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProfilePrivacyRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ProfilePrivacyRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *ProfilePrivacyRepo_Expecter) Get(ctx interface{}, userID interface{}) *ProfilePrivacyRepo_Get_Call {
	return &ProfilePrivacyRepo_Get_Call{Call: _e.mock.On("Get", ctx, userID)}
}

func (_c *ProfilePrivacyRepo_Get_Call) Run(run func(ctx context.Context, userID int64)) *ProfilePrivacyRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ProfilePrivacyRepo_Get_Call) Return(_a0 domain.ProfilePrivacy, _a1 error) *ProfilePrivacyRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProfilePrivacyRepo_Get_Call) RunAndReturn(run func(context.Context, int64) (domain.ProfilePrivacy, error)) *ProfilePrivacyRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, p
func (_m *ProfilePrivacyRepo) Update(ctx context.Context, p domain.ProfilePrivacy) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ProfilePrivacy) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProfilePrivacyRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProfilePrivacyRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.ProfilePrivacy
func (_e *ProfilePrivacyRepo_Expecter) Update(ctx interface{}, p interface{}) *ProfilePrivacyRepo_Update_Call {
	return &ProfilePrivacyRepo_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *ProfilePrivacyRepo_Update_Call) Run(run func(ctx context.Context, p domain.ProfilePrivacy)) *ProfilePrivacyRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ProfilePrivacy))
	})
	return _c
}

func (_c *ProfilePrivacyRepo_Update_Call) Return(_a0 error) *ProfilePrivacyRepo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfilePrivacyRepo_Update_Call) RunAndReturn(run func(context.Context, domain.ProfilePrivacy) error) *ProfilePrivacyRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewProfilePrivacyRepo creates a new instance of ProfilePrivacyRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfilePrivacyRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfilePrivacyRepo {
	mock := &ProfilePrivacyRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
