// Code generated by mockery v2.53.6. DO NOT EDIT.

package profilemocks

import (
	context "context"

	domain "github.com/iamsalnikov/nastene/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/iamsalnikov/nastene/internal/repository"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

type UserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepo) EXPECT() *UserRepo_Expecter {
	return &UserRepo_Expecter{mock: &_m.Mock}
}

// ByID provides a mock function with given fields: ctx, id
func (_m *UserRepo) ByID(ctx context.Context, id int64) (domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type UserRepo_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UserRepo_Expecter) ByID(ctx interface{}, id interface{}) *UserRepo_ByID_Call {
	return &UserRepo_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *UserRepo_ByID_Call) Run(run func(ctx context.Context, id int64)) *UserRepo_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UserRepo_ByID_Call) Return(_a0 domain.User, _a1 error) *UserRepo_ByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepo_ByID_Call) RunAndReturn(run func(context.Context, int64) (domain.User, error)) *UserRepo_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAvatar provides a mock function with given fields: ctx, userID, path
func (_m *UserRepo) UpdateAvatar(ctx context.Context, userID int64, path string) error {
	ret := _m.Called(ctx, userID, path)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, userID, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepo_UpdateAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAvatar'
type UserRepo_UpdateAvatar_Call struct {
	*mock.Call
}

// UpdateAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - path string
func (_e *UserRepo_Expecter) UpdateAvatar(ctx interface{}, userID interface{}, path interface{}) *UserRepo_UpdateAvatar_Call {
	return &UserRepo_UpdateAvatar_Call{Call: _e.mock.On("UpdateAvatar", ctx, userID, path)}
}

func (_c *UserRepo_UpdateAvatar_Call) Run(run func(ctx context.Context, userID int64, path string)) *UserRepo_UpdateAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *UserRepo_UpdateAvatar_Call) Return(_a0 error) *UserRepo_UpdateAvatar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepo_UpdateAvatar_Call) RunAndReturn(run func(context.Context, int64, string) error) *UserRepo_UpdateAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, userID, p
func (_m *UserRepo) UpdateProfile(ctx context.Context, userID int64, p repository.ProfileFields) error {
	ret := _m.Called(ctx, userID, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, repository.ProfileFields) error); ok {
		r0 = rf(ctx, userID, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepo_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type UserRepo_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - p repository.ProfileFields
func (_e *UserRepo_Expecter) UpdateProfile(ctx interface{}, userID interface{}, p interface{}) *UserRepo_UpdateProfile_Call {
	return &UserRepo_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, p)}
}

func (_c *UserRepo_UpdateProfile_Call) Run(run func(ctx context.Context, userID int64, p repository.ProfileFields)) *UserRepo_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(repository.ProfileFields))
	})
	return _c
}

func (_c *UserRepo_UpdateProfile_Call) Return(_a0 error) *UserRepo_UpdateProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepo_UpdateProfile_Call) RunAndReturn(run func(context.Context, int64, repository.ProfileFields) error) *UserRepo_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
