// Code generated by mockery v2.53.6. DO NOT EDIT.

package newsmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AvatarAuthorizer is an autogenerated mock type for the AvatarAuthorizer type
type AvatarAuthorizer struct {
	mock.Mock
}

type AvatarAuthorizer_Expecter struct {
	mock *mock.Mock
}

func (_m *AvatarAuthorizer) EXPECT() *AvatarAuthorizer_Expecter {
	return &AvatarAuthorizer_Expecter{mock: &_m.Mock}
}

// CanSeeAvatar provides a mock function with given fields: ctx, viewerID, ownerID
func (_m *AvatarAuthorizer) CanSeeAvatar(ctx context.Context, viewerID int64, ownerID int64) (bool, error) {
	ret := _m.Called(ctx, viewerID, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for CanSeeAvatar")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (bool, error)); ok {
		return rf(ctx, viewerID, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) bool); ok {
		r0 = rf(ctx, viewerID, ownerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, viewerID, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AvatarAuthorizer_CanSeeAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanSeeAvatar'
type AvatarAuthorizer_CanSeeAvatar_Call struct {
	*mock.Call
}

// CanSeeAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - viewerID int64
//   - ownerID int64
func (_e *AvatarAuthorizer_Expecter) CanSeeAvatar(ctx interface{}, viewerID interface{}, ownerID interface{}) *AvatarAuthorizer_CanSeeAvatar_Call {
	return &AvatarAuthorizer_CanSeeAvatar_Call{Call: _e.mock.On("CanSeeAvatar", ctx, viewerID, ownerID)}
}

func (_c *AvatarAuthorizer_CanSeeAvatar_Call) Run(run func(ctx context.Context, viewerID int64, ownerID int64)) *AvatarAuthorizer_CanSeeAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *AvatarAuthorizer_CanSeeAvatar_Call) Return(_a0 bool, _a1 error) *AvatarAuthorizer_CanSeeAvatar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AvatarAuthorizer_CanSeeAvatar_Call) RunAndReturn(run func(context.Context, int64, int64) (bool, error)) *AvatarAuthorizer_CanSeeAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// NewAvatarAuthorizer creates a new instance of AvatarAuthorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAvatarAuthorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AvatarAuthorizer {
	mock := &AvatarAuthorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
