// Code generated by mockery v2.53.6. DO NOT EDIT.

package newsmocks

import (
	context "context"

	domain "github.com/iamsalnikov/nastene/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// FeedRepo is an autogenerated mock type for the FeedRepo type
type FeedRepo struct {
	mock.Mock
}

type FeedRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *FeedRepo) EXPECT() *FeedRepo_Expecter {
	return &FeedRepo_Expecter{mock: &_m.Mock}
}

// ListFeed provides a mock function with given fields: ctx, userID, limit, offset
func (_m *FeedRepo) ListFeed(ctx context.Context, userID int64, limit int, offset int) ([]domain.NewsEvent, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListFeed")
	}

	var r0 []domain.NewsEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]domain.NewsEvent, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) []domain.NewsEvent); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.NewsEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FeedRepo_ListFeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFeed'
type FeedRepo_ListFeed_Call struct {
	*mock.Call
}

// ListFeed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - limit int
//   - offset int
func (_e *FeedRepo_Expecter) ListFeed(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *FeedRepo_ListFeed_Call {
	return &FeedRepo_ListFeed_Call{Call: _e.mock.On("ListFeed", ctx, userID, limit, offset)}
}

func (_c *FeedRepo_ListFeed_Call) Run(run func(ctx context.Context, userID int64, limit int, offset int)) *FeedRepo_ListFeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *FeedRepo_ListFeed_Call) Return(_a0 []domain.NewsEvent, _a1 error) *FeedRepo_ListFeed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FeedRepo_ListFeed_Call) RunAndReturn(run func(context.Context, int64, int, int) ([]domain.NewsEvent, error)) *FeedRepo_ListFeed_Call {
	_c.Call.Return(run)
	return _c
}

// NewFeedRepo creates a new instance of FeedRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFeedRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *FeedRepo {
	mock := &FeedRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
