// Code generated by mockery v2.53.6. DO NOT EDIT.

package newsfeedmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Authorizer is an autogenerated mock type for the Authorizer type
type Authorizer struct {
	mock.Mock
}

type Authorizer_Expecter struct {
	mock *mock.Mock
}

func (_m *Authorizer) EXPECT() *Authorizer_Expecter {
	return &Authorizer_Expecter{mock: &_m.Mock}
}

// CanView provides a mock function with given fields: ctx, viewerID, ownerID
func (_m *Authorizer) CanView(ctx context.Context, viewerID int64, ownerID int64) (bool, error) {
	ret := _m.Called(ctx, viewerID, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for CanView")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (bool, error)); ok {
		return rf(ctx, viewerID, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) bool); ok {
		r0 = rf(ctx, viewerID, ownerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, viewerID, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Authorizer_CanView_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanView'
type Authorizer_CanView_Call struct {
	*mock.Call
}

// CanView is a helper method to define mock.On call
//   - ctx context.Context
//   - viewerID int64
//   - ownerID int64
func (_e *Authorizer_Expecter) CanView(ctx interface{}, viewerID interface{}, ownerID interface{}) *Authorizer_CanView_Call {
	return &Authorizer_CanView_Call{Call: _e.mock.On("CanView", ctx, viewerID, ownerID)}
}

func (_c *Authorizer_CanView_Call) Run(run func(ctx context.Context, viewerID int64, ownerID int64)) *Authorizer_CanView_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *Authorizer_CanView_Call) Return(_a0 bool, _a1 error) *Authorizer_CanView_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Authorizer_CanView_Call) RunAndReturn(run func(context.Context, int64, int64) (bool, error)) *Authorizer_CanView_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthorizer creates a new instance of Authorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Authorizer {
	mock := &Authorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
