// Code generated by mockery v2.53.6. DO NOT EDIT.

package newsfeedmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BanChecker is an autogenerated mock type for the BanChecker type
type BanChecker struct {
	mock.Mock
}

type BanChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *BanChecker) EXPECT() *BanChecker_Expecter {
	return &BanChecker_Expecter{mock: &_m.Mock}
}

// IsBanned provides a mock function with given fields: ctx, ownerID, otherID
func (_m *BanChecker) IsBanned(ctx context.Context, ownerID int64, otherID int64) (bool, error) {
	ret := _m.Called(ctx, ownerID, otherID)

	if len(ret) == 0 {
		panic("no return value specified for IsBanned")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (bool, error)); ok {
		return rf(ctx, ownerID, otherID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) bool); ok {
		r0 = rf(ctx, ownerID, otherID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, ownerID, otherID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BanChecker_IsBanned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBanned'
type BanChecker_IsBanned_Call struct {
	*mock.Call
}

// IsBanned is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID int64
//   - otherID int64
func (_e *BanChecker_Expecter) IsBanned(ctx interface{}, ownerID interface{}, otherID interface{}) *BanChecker_IsBanned_Call {
	return &BanChecker_IsBanned_Call{Call: _e.mock.On("IsBanned", ctx, ownerID, otherID)}
}

func (_c *BanChecker_IsBanned_Call) Run(run func(ctx context.Context, ownerID int64, otherID int64)) *BanChecker_IsBanned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *BanChecker_IsBanned_Call) Return(_a0 bool, _a1 error) *BanChecker_IsBanned_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BanChecker_IsBanned_Call) RunAndReturn(run func(context.Context, int64, int64) (bool, error)) *BanChecker_IsBanned_Call {
	_c.Call.Return(run)
	return _c
}

// NewBanChecker creates a new instance of BanChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBanChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *BanChecker {
	mock := &BanChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
