// Code generated by mockery v2.53.6. DO NOT EDIT.

package newsfeedmocks

import (
	context "context"

	domain "github.com/iamsalnikov/nastene/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// CommentRepo is an autogenerated mock type for the CommentRepo type
type CommentRepo struct {
	mock.Mock
}

type CommentRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *CommentRepo) EXPECT() *CommentRepo_Expecter {
	return &CommentRepo_Expecter{mock: &_m.Mock}
}

// ByID provides a mock function with given fields: ctx, id
func (_m *CommentRepo) ByID(ctx context.Context, id int64) (domain.Comment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 domain.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Comment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Comment); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommentRepo_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type CommentRepo_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *CommentRepo_Expecter) ByID(ctx interface{}, id interface{}) *CommentRepo_ByID_Call {
	return &CommentRepo_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *CommentRepo_ByID_Call) Run(run func(ctx context.Context, id int64)) *CommentRepo_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *CommentRepo_ByID_Call) Return(_a0 domain.Comment, _a1 error) *CommentRepo_ByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CommentRepo_ByID_Call) RunAndReturn(run func(context.Context, int64) (domain.Comment, error)) *CommentRepo_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// DistinctAuthorsByPost provides a mock function with given fields: ctx, postID, excludeAuthorID
func (_m *CommentRepo) DistinctAuthorsByPost(ctx context.Context, postID int64, excludeAuthorID int64) ([]int64, error) {
	ret := _m.Called(ctx, postID, excludeAuthorID)

	if len(ret) == 0 {
		panic("no return value specified for DistinctAuthorsByPost")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) ([]int64, error)); ok {
		return rf(ctx, postID, excludeAuthorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) []int64); ok {
		r0 = rf(ctx, postID, excludeAuthorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, postID, excludeAuthorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommentRepo_DistinctAuthorsByPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DistinctAuthorsByPost'
type CommentRepo_DistinctAuthorsByPost_Call struct {
	*mock.Call
}

// DistinctAuthorsByPost is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
//   - excludeAuthorID int64
func (_e *CommentRepo_Expecter) DistinctAuthorsByPost(ctx interface{}, postID interface{}, excludeAuthorID interface{}) *CommentRepo_DistinctAuthorsByPost_Call {
	return &CommentRepo_DistinctAuthorsByPost_Call{Call: _e.mock.On("DistinctAuthorsByPost", ctx, postID, excludeAuthorID)}
}

func (_c *CommentRepo_DistinctAuthorsByPost_Call) Run(run func(ctx context.Context, postID int64, excludeAuthorID int64)) *CommentRepo_DistinctAuthorsByPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *CommentRepo_DistinctAuthorsByPost_Call) Return(_a0 []int64, _a1 error) *CommentRepo_DistinctAuthorsByPost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CommentRepo_DistinctAuthorsByPost_Call) RunAndReturn(run func(context.Context, int64, int64) ([]int64, error)) *CommentRepo_DistinctAuthorsByPost_Call {
	_c.Call.Return(run)
	return _c
}

// NewCommentRepo creates a new instance of CommentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentRepo {
	mock := &CommentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
