// Code generated by mockery v2.53.6. DO NOT EDIT.

package newsfeedmocks

import (
	context "context"

	newsfeed "github.com/iamsalnikov/nastene/internal/service/newsfeed"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// FeedRepo is an autogenerated mock type for the FeedRepo type
type FeedRepo struct {
	mock.Mock
}

type FeedRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *FeedRepo) EXPECT() *FeedRepo_Expecter {
	return &FeedRepo_Expecter{mock: &_m.Mock}
}

// DeleteForBan provides a mock function with given fields: ctx, a, b
func (_m *FeedRepo) DeleteForBan(ctx context.Context, a int64, b int64) error {
	ret := _m.Called(ctx, a, b)

	if len(ret) == 0 {
		panic("no return value specified for DeleteForBan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, a, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FeedRepo_DeleteForBan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteForBan'
type FeedRepo_DeleteForBan_Call struct {
	*mock.Call
}

// DeleteForBan is a helper method to define mock.On call
//   - ctx context.Context
//   - a int64
//   - b int64
func (_e *FeedRepo_Expecter) DeleteForBan(ctx interface{}, a interface{}, b interface{}) *FeedRepo_DeleteForBan_Call {
	return &FeedRepo_DeleteForBan_Call{Call: _e.mock.On("DeleteForBan", ctx, a, b)}
}

func (_c *FeedRepo_DeleteForBan_Call) Run(run func(ctx context.Context, a int64, b int64)) *FeedRepo_DeleteForBan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *FeedRepo_DeleteForBan_Call) Return(_a0 error) *FeedRepo_DeleteForBan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FeedRepo_DeleteForBan_Call) RunAndReturn(run func(context.Context, int64, int64) error) *FeedRepo_DeleteForBan_Call {
	_c.Call.Return(run)
	return _c
}

// DistinctViewersForOwner provides a mock function with given fields: ctx, ownerID
func (_m *FeedRepo) DistinctViewersForOwner(ctx context.Context, ownerID int64) ([]int64, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for DistinctViewersForOwner")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]int64, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []int64); ok {
		r0 = rf(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FeedRepo_DistinctViewersForOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DistinctViewersForOwner'
type FeedRepo_DistinctViewersForOwner_Call struct {
	*mock.Call
}

// DistinctViewersForOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID int64
func (_e *FeedRepo_Expecter) DistinctViewersForOwner(ctx interface{}, ownerID interface{}) *FeedRepo_DistinctViewersForOwner_Call {
	return &FeedRepo_DistinctViewersForOwner_Call{Call: _e.mock.On("DistinctViewersForOwner", ctx, ownerID)}
}

func (_c *FeedRepo_DistinctViewersForOwner_Call) Run(run func(ctx context.Context, ownerID int64)) *FeedRepo_DistinctViewersForOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *FeedRepo_DistinctViewersForOwner_Call) Return(_a0 []int64, _a1 error) *FeedRepo_DistinctViewersForOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FeedRepo_DistinctViewersForOwner_Call) RunAndReturn(run func(context.Context, int64) ([]int64, error)) *FeedRepo_DistinctViewersForOwner_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, row
func (_m *FeedRepo) Insert(ctx context.Context, row newsfeed.FeedRow) error {
	ret := _m.Called(ctx, row)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, newsfeed.FeedRow) error); ok {
		r0 = rf(ctx, row)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FeedRepo_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type FeedRepo_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - row newsfeed.FeedRow
func (_e *FeedRepo_Expecter) Insert(ctx interface{}, row interface{}) *FeedRepo_Insert_Call {
	return &FeedRepo_Insert_Call{Call: _e.mock.On("Insert", ctx, row)}
}

func (_c *FeedRepo_Insert_Call) Run(run func(ctx context.Context, row newsfeed.FeedRow)) *FeedRepo_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(newsfeed.FeedRow))
	})
	return _c
}

func (_c *FeedRepo_Insert_Call) Return(_a0 error) *FeedRepo_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FeedRepo_Insert_Call) RunAndReturn(run func(context.Context, newsfeed.FeedRow) error) *FeedRepo_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// SetHiddenForOwner provides a mock function with given fields: ctx, ownerID, userIDs, now
func (_m *FeedRepo) SetHiddenForOwner(ctx context.Context, ownerID int64, userIDs []int64, now time.Time) error {
	ret := _m.Called(ctx, ownerID, userIDs, now)

	if len(ret) == 0 {
		panic("no return value specified for SetHiddenForOwner")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []int64, time.Time) error); ok {
		r0 = rf(ctx, ownerID, userIDs, now)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FeedRepo_SetHiddenForOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHiddenForOwner'
type FeedRepo_SetHiddenForOwner_Call struct {
	*mock.Call
}

// SetHiddenForOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID int64
//   - userIDs []int64
//   - now time.Time
func (_e *FeedRepo_Expecter) SetHiddenForOwner(ctx interface{}, ownerID interface{}, userIDs interface{}, now interface{}) *FeedRepo_SetHiddenForOwner_Call {
	return &FeedRepo_SetHiddenForOwner_Call{Call: _e.mock.On("SetHiddenForOwner", ctx, ownerID, userIDs, now)}
}

func (_c *FeedRepo_SetHiddenForOwner_Call) Run(run func(ctx context.Context, ownerID int64, userIDs []int64, now time.Time)) *FeedRepo_SetHiddenForOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]int64), args[3].(time.Time))
	})
	return _c
}

func (_c *FeedRepo_SetHiddenForOwner_Call) Return(_a0 error) *FeedRepo_SetHiddenForOwner_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FeedRepo_SetHiddenForOwner_Call) RunAndReturn(run func(context.Context, int64, []int64, time.Time) error) *FeedRepo_SetHiddenForOwner_Call {
	_c.Call.Return(run)
	return _c
}

// SetVisibleForOwner provides a mock function with given fields: ctx, ownerID, userIDs
func (_m *FeedRepo) SetVisibleForOwner(ctx context.Context, ownerID int64, userIDs []int64) error {
	ret := _m.Called(ctx, ownerID, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for SetVisibleForOwner")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []int64) error); ok {
		r0 = rf(ctx, ownerID, userIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FeedRepo_SetVisibleForOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVisibleForOwner'
type FeedRepo_SetVisibleForOwner_Call struct {
	*mock.Call
}

// SetVisibleForOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID int64
//   - userIDs []int64
func (_e *FeedRepo_Expecter) SetVisibleForOwner(ctx interface{}, ownerID interface{}, userIDs interface{}) *FeedRepo_SetVisibleForOwner_Call {
	return &FeedRepo_SetVisibleForOwner_Call{Call: _e.mock.On("SetVisibleForOwner", ctx, ownerID, userIDs)}
}

func (_c *FeedRepo_SetVisibleForOwner_Call) Run(run func(ctx context.Context, ownerID int64, userIDs []int64)) *FeedRepo_SetVisibleForOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]int64))
	})
	return _c
}

func (_c *FeedRepo_SetVisibleForOwner_Call) Return(_a0 error) *FeedRepo_SetVisibleForOwner_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FeedRepo_SetVisibleForOwner_Call) RunAndReturn(run func(context.Context, int64, []int64) error) *FeedRepo_SetVisibleForOwner_Call {
	_c.Call.Return(run)
	return _c
}

// NewFeedRepo creates a new instance of FeedRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFeedRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *FeedRepo {
	mock := &FeedRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
