// Code generated by mockery v2.53.6. DO NOT EDIT.

package newsfeedmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// FriendRepo is an autogenerated mock type for the FriendRepo type
type FriendRepo struct {
	mock.Mock
}

type FriendRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *FriendRepo) EXPECT() *FriendRepo_Expecter {
	return &FriendRepo_Expecter{mock: &_m.Mock}
}

// ListFriendIDs provides a mock function with given fields: ctx, userID
func (_m *FriendRepo) ListFriendIDs(ctx context.Context, userID int64) ([]int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListFriendIDs")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []int64); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FriendRepo_ListFriendIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFriendIDs'
type FriendRepo_ListFriendIDs_Call struct {
	*mock.Call
}

// ListFriendIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *FriendRepo_Expecter) ListFriendIDs(ctx interface{}, userID interface{}) *FriendRepo_ListFriendIDs_Call {
	return &FriendRepo_ListFriendIDs_Call{Call: _e.mock.On("ListFriendIDs", ctx, userID)}
}

func (_c *FriendRepo_ListFriendIDs_Call) Run(run func(ctx context.Context, userID int64)) *FriendRepo_ListFriendIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *FriendRepo_ListFriendIDs_Call) Return(_a0 []int64, _a1 error) *FriendRepo_ListFriendIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FriendRepo_ListFriendIDs_Call) RunAndReturn(run func(context.Context, int64) ([]int64, error)) *FriendRepo_ListFriendIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewFriendRepo creates a new instance of FriendRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFriendRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *FriendRepo {
	mock := &FriendRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
