// Code generated by mockery v2.53.6. DO NOT EDIT.

package newsfeedmocks

import (
	context "context"

	domain "github.com/iamsalnikov/nastene/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// PostRepo is an autogenerated mock type for the PostRepo type
type PostRepo struct {
	mock.Mock
}

type PostRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *PostRepo) EXPECT() *PostRepo_Expecter {
	return &PostRepo_Expecter{mock: &_m.Mock}
}

// ByID provides a mock function with given fields: ctx, id
func (_m *PostRepo) ByID(ctx context.Context, id int64) (domain.WallPost, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 domain.WallPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.WallPost, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.WallPost); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.WallPost)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostRepo_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type PostRepo_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *PostRepo_Expecter) ByID(ctx interface{}, id interface{}) *PostRepo_ByID_Call {
	return &PostRepo_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *PostRepo_ByID_Call) Run(run func(ctx context.Context, id int64)) *PostRepo_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PostRepo_ByID_Call) Return(_a0 domain.WallPost, _a1 error) *PostRepo_ByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PostRepo_ByID_Call) RunAndReturn(run func(context.Context, int64) (domain.WallPost, error)) *PostRepo_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewPostRepo creates a new instance of PostRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostRepo {
	mock := &PostRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
