// Code generated by mockery v2.53.6. DO NOT EDIT.

package privacymocks

import (
	context "context"

	domain "github.com/iamsalnikov/nastene/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

type Repo_Expecter struct {
	mock *mock.Mock
}

func (_m *Repo) EXPECT() *Repo_Expecter {
	return &Repo_Expecter{mock: &_m.Mock}
}

// EnsureDefaults provides a mock function with given fields: ctx, userID
func (_m *Repo) EnsureDefaults(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for EnsureDefaults")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_EnsureDefaults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureDefaults'
type Repo_EnsureDefaults_Call struct {
	*mock.Call
}

// EnsureDefaults is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Repo_Expecter) EnsureDefaults(ctx interface{}, userID interface{}) *Repo_EnsureDefaults_Call {
	return &Repo_EnsureDefaults_Call{Call: _e.mock.On("EnsureDefaults", ctx, userID)}
}

func (_c *Repo_EnsureDefaults_Call) Run(run func(ctx context.Context, userID int64)) *Repo_EnsureDefaults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Repo_EnsureDefaults_Call) Return(_a0 error) *Repo_EnsureDefaults_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_EnsureDefaults_Call) RunAndReturn(run func(context.Context, int64) error) *Repo_EnsureDefaults_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, userID
func (_m *Repo) Get(ctx context.Context, userID int64) (domain.WallPrivacy, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.WallPrivacy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.WallPrivacy, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.WallPrivacy); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.WallPrivacy)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Repo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *Repo_Expecter) Get(ctx interface{}, userID interface{}) *Repo_Get_Call {
	return &Repo_Get_Call{Call: _e.mock.On("Get", ctx, userID)}
}

func (_c *Repo_Get_Call) Run(run func(ctx context.Context, userID int64)) *Repo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Repo_Get_Call) Return(_a0 domain.WallPrivacy, _a1 error) *Repo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_Get_Call) RunAndReturn(run func(context.Context, int64) (domain.WallPrivacy, error)) *Repo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, view, post, comment
func (_m *Repo) Update(ctx context.Context, userID int64, view domain.WallScope, post domain.WallScope, comment domain.WallScope) error {
	ret := _m.Called(ctx, userID, view, post, comment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.WallScope, domain.WallScope, domain.WallScope) error); ok {
		r0 = rf(ctx, userID, view, post, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - view domain.WallScope
//   - post domain.WallScope
//   - comment domain.WallScope
func (_e *Repo_Expecter) Update(ctx interface{}, userID interface{}, view interface{}, post interface{}, comment interface{}) *Repo_Update_Call {
	return &Repo_Update_Call{Call: _e.mock.On("Update", ctx, userID, view, post, comment)}
}

func (_c *Repo_Update_Call) Run(run func(ctx context.Context, userID int64, view domain.WallScope, post domain.WallScope, comment domain.WallScope)) *Repo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.WallScope), args[3].(domain.WallScope), args[4].(domain.WallScope))
	})
	return _c
}

func (_c *Repo_Update_Call) Return(_a0 error) *Repo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_Update_Call) RunAndReturn(run func(context.Context, int64, domain.WallScope, domain.WallScope, domain.WallScope) error) *Repo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
