// Code generated by mockery v2.53.6. DO NOT EDIT.

package bansmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// FriendRepo is an autogenerated mock type for the FriendRepo type
type FriendRepo struct {
	mock.Mock
}

type FriendRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *FriendRepo) EXPECT() *FriendRepo_Expecter {
	return &FriendRepo_Expecter{mock: &_m.Mock}
}

// RemoveFriendship provides a mock function with given fields: ctx, a, b
func (_m *FriendRepo) RemoveFriendship(ctx context.Context, a int64, b int64) error {
	ret := _m.Called(ctx, a, b)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFriendship")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, a, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FriendRepo_RemoveFriendship_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFriendship'
type FriendRepo_RemoveFriendship_Call struct {
	*mock.Call
}

// RemoveFriendship is a helper method to define mock.On call
//   - ctx context.Context
//   - a int64
//   - b int64
func (_e *FriendRepo_Expecter) RemoveFriendship(ctx interface{}, a interface{}, b interface{}) *FriendRepo_RemoveFriendship_Call {
	return &FriendRepo_RemoveFriendship_Call{Call: _e.mock.On("RemoveFriendship", ctx, a, b)}
}

func (_c *FriendRepo_RemoveFriendship_Call) Run(run func(ctx context.Context, a int64, b int64)) *FriendRepo_RemoveFriendship_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *FriendRepo_RemoveFriendship_Call) Return(_a0 error) *FriendRepo_RemoveFriendship_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FriendRepo_RemoveFriendship_Call) RunAndReturn(run func(context.Context, int64, int64) error) *FriendRepo_RemoveFriendship_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveRequest provides a mock function with given fields: ctx, fromID, toID
func (_m *FriendRepo) RemoveRequest(ctx context.Context, fromID int64, toID int64) error {
	ret := _m.Called(ctx, fromID, toID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, fromID, toID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FriendRepo_RemoveRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRequest'
type FriendRepo_RemoveRequest_Call struct {
	*mock.Call
}

// RemoveRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - fromID int64
//   - toID int64
func (_e *FriendRepo_Expecter) RemoveRequest(ctx interface{}, fromID interface{}, toID interface{}) *FriendRepo_RemoveRequest_Call {
	return &FriendRepo_RemoveRequest_Call{Call: _e.mock.On("RemoveRequest", ctx, fromID, toID)}
}

func (_c *FriendRepo_RemoveRequest_Call) Run(run func(ctx context.Context, fromID int64, toID int64)) *FriendRepo_RemoveRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *FriendRepo_RemoveRequest_Call) Return(_a0 error) *FriendRepo_RemoveRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FriendRepo_RemoveRequest_Call) RunAndReturn(run func(context.Context, int64, int64) error) *FriendRepo_RemoveRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewFriendRepo creates a new instance of FriendRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFriendRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *FriendRepo {
	mock := &FriendRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
