// Code generated by mockery v2.53.6. DO NOT EDIT.

package bansmocks

import (
	context "context"

	domain "github.com/iamsalnikov/nastene/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

type Repo_Expecter struct {
	mock *mock.Mock
}

func (_m *Repo) EXPECT() *Repo_Expecter {
	return &Repo_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, ownerID, bannedID
func (_m *Repo) Add(ctx context.Context, ownerID int64, bannedID int64) error {
	ret := _m.Called(ctx, ownerID, bannedID)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, ownerID, bannedID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Repo_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID int64
//   - bannedID int64
func (_e *Repo_Expecter) Add(ctx interface{}, ownerID interface{}, bannedID interface{}) *Repo_Add_Call {
	return &Repo_Add_Call{Call: _e.mock.On("Add", ctx, ownerID, bannedID)}
}

func (_c *Repo_Add_Call) Run(run func(ctx context.Context, ownerID int64, bannedID int64)) *Repo_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *Repo_Add_Call) Return(_a0 error) *Repo_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_Add_Call) RunAndReturn(run func(context.Context, int64, int64) error) *Repo_Add_Call {
	_c.Call.Return(run)
	return _c
}

// IsBanned provides a mock function with given fields: ctx, ownerID, otherID
func (_m *Repo) IsBanned(ctx context.Context, ownerID int64, otherID int64) (bool, error) {
	ret := _m.Called(ctx, ownerID, otherID)

	if len(ret) == 0 {
		panic("no return value specified for IsBanned")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (bool, error)); ok {
		return rf(ctx, ownerID, otherID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) bool); ok {
		r0 = rf(ctx, ownerID, otherID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, ownerID, otherID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_IsBanned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBanned'
type Repo_IsBanned_Call struct {
	*mock.Call
}

// IsBanned is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID int64
//   - otherID int64
func (_e *Repo_Expecter) IsBanned(ctx interface{}, ownerID interface{}, otherID interface{}) *Repo_IsBanned_Call {
	return &Repo_IsBanned_Call{Call: _e.mock.On("IsBanned", ctx, ownerID, otherID)}
}

func (_c *Repo_IsBanned_Call) Run(run func(ctx context.Context, ownerID int64, otherID int64)) *Repo_IsBanned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *Repo_IsBanned_Call) Return(_a0 bool, _a1 error) *Repo_IsBanned_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_IsBanned_Call) RunAndReturn(run func(context.Context, int64, int64) (bool, error)) *Repo_IsBanned_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOwner provides a mock function with given fields: ctx, ownerID
func (_m *Repo) ListByOwner(ctx context.Context, ownerID int64) ([]domain.Ban, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByOwner")
	}

	var r0 []domain.Ban
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]domain.Ban, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.Ban); ok {
		r0 = rf(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Ban)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_ListByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOwner'
type Repo_ListByOwner_Call struct {
	*mock.Call
}

// ListByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID int64
func (_e *Repo_Expecter) ListByOwner(ctx interface{}, ownerID interface{}) *Repo_ListByOwner_Call {
	return &Repo_ListByOwner_Call{Call: _e.mock.On("ListByOwner", ctx, ownerID)}
}

func (_c *Repo_ListByOwner_Call) Run(run func(ctx context.Context, ownerID int64)) *Repo_ListByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Repo_ListByOwner_Call) Return(_a0 []domain.Ban, _a1 error) *Repo_ListByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_ListByOwner_Call) RunAndReturn(run func(context.Context, int64) ([]domain.Ban, error)) *Repo_ListByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, ownerID, bannedID
func (_m *Repo) Remove(ctx context.Context, ownerID int64, bannedID int64) error {
	ret := _m.Called(ctx, ownerID, bannedID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, ownerID, bannedID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type Repo_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID int64
//   - bannedID int64
func (_e *Repo_Expecter) Remove(ctx interface{}, ownerID interface{}, bannedID interface{}) *Repo_Remove_Call {
	return &Repo_Remove_Call{Call: _e.mock.On("Remove", ctx, ownerID, bannedID)}
}

func (_c *Repo_Remove_Call) Run(run func(ctx context.Context, ownerID int64, bannedID int64)) *Repo_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *Repo_Remove_Call) Return(_a0 error) *Repo_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_Remove_Call) RunAndReturn(run func(context.Context, int64, int64) error) *Repo_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
