// Code generated by mockery v2.53.6. DO NOT EDIT.

package authmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// FriendRequester is an autogenerated mock type for the FriendRequester type
type FriendRequester struct {
	mock.Mock
}

type FriendRequester_Expecter struct {
	mock *mock.Mock
}

func (_m *FriendRequester) EXPECT() *FriendRequester_Expecter {
	return &FriendRequester_Expecter{mock: &_m.Mock}
}

// SendRequest provides a mock function with given fields: ctx, fromID, toID
func (_m *FriendRequester) SendRequest(ctx context.Context, fromID int64, toID int64) error {
	ret := _m.Called(ctx, fromID, toID)

	if len(ret) == 0 {
		panic("no return value specified for SendRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, fromID, toID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FriendRequester_SendRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRequest'
type FriendRequester_SendRequest_Call struct {
	*mock.Call
}

// SendRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - fromID int64
//   - toID int64
func (_e *FriendRequester_Expecter) SendRequest(ctx interface{}, fromID interface{}, toID interface{}) *FriendRequester_SendRequest_Call {
	return &FriendRequester_SendRequest_Call{Call: _e.mock.On("SendRequest", ctx, fromID, toID)}
}

func (_c *FriendRequester_SendRequest_Call) Run(run func(ctx context.Context, fromID int64, toID int64)) *FriendRequester_SendRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *FriendRequester_SendRequest_Call) Return(_a0 error) *FriendRequester_SendRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FriendRequester_SendRequest_Call) RunAndReturn(run func(context.Context, int64, int64) error) *FriendRequester_SendRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewFriendRequester creates a new instance of FriendRequester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFriendRequester(t interface {
	mock.TestingT
	Cleanup(func())
}) *FriendRequester {
	mock := &FriendRequester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
