// Code generated by mockery v2.53.6. DO NOT EDIT.

package authmocks

import (
	context "context"

	domain "github.com/iamsalnikov/nastene/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

type UserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepo) EXPECT() *UserRepo_Expecter {
	return &UserRepo_Expecter{mock: &_m.Mock}
}

// ByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepo) ByEmail(ctx context.Context, email string) (domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ByEmail")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_ByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByEmail'
type UserRepo_ByEmail_Call struct {
	*mock.Call
}

// ByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepo_Expecter) ByEmail(ctx interface{}, email interface{}) *UserRepo_ByEmail_Call {
	return &UserRepo_ByEmail_Call{Call: _e.mock.On("ByEmail", ctx, email)}
}

func (_c *UserRepo_ByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepo_ByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepo_ByEmail_Call) Return(_a0 domain.User, _a1 error) *UserRepo_ByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepo_ByEmail_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *UserRepo_ByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, email, passwordHash, displayName
func (_m *UserRepo) Create(ctx context.Context, email string, passwordHash string, displayName string) (domain.User, error) {
	ret := _m.Called(ctx, email, passwordHash, displayName)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (domain.User, error)); ok {
		return rf(ctx, email, passwordHash, displayName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) domain.User); ok {
		r0 = rf(ctx, email, passwordHash, displayName)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, passwordHash, displayName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passwordHash string
//   - displayName string
func (_e *UserRepo_Expecter) Create(ctx interface{}, email interface{}, passwordHash interface{}, displayName interface{}) *UserRepo_Create_Call {
	return &UserRepo_Create_Call{Call: _e.mock.On("Create", ctx, email, passwordHash, displayName)}
}

func (_c *UserRepo_Create_Call) Run(run func(ctx context.Context, email string, passwordHash string, displayName string)) *UserRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *UserRepo_Create_Call) Return(_a0 domain.User, _a1 error) *UserRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepo_Create_Call) RunAndReturn(run func(context.Context, string, string, string) (domain.User, error)) *UserRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
